version: "3.9"
services:
  node-server:
    restart: always
    build:
      context: ./app
  web-server:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - node-server
